NAME = libft.a
CC = cc
FLAGS = -Wall -Wextra -Werror
SRC = ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c \
      ft_isprint.c ft_strdup.c ft_calloc.c ft_strnstr.c ft_memcmp.c \
      ft_memchr.c ft_memcpy.c ft_memset.c ft_strchr.c ft_strlcat.c \
      ft_strlcpy.c ft_strlen.c ft_strncmp.c ft_strrchr.c ft_tolower.c \
      ft_toupper.c ft_memmove.c ft_atoi.c ft_substr.c ft_strjoin.c \
      ft_strtrim.c ft_split.c ft_itoa.c ft_putchar_fd.c ft_putstr_fd.c \
      ft_putnbr_fd.c ft_putendl_fd.c ft_striteri.c ft_strmapi.c
OBJ = $(SRC:.c=.o)
SRC2 = ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c \
	   ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
	   ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c
BONUS_OBJ = $(SRC2:.c=.o)

all: $(NAME) 

%.o: %.c libft.h
	$(CC) -c $< -o $@ $(FLAGS)

$(NAME): $(OBJ)
	ar rc $(NAME) $(OBJ)

clean:
	rm -f $(OBJ) $(BONUS_OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

bonus:	$(OBJ) $(BONUS_OBJ)
	ar rc $(NAME) $(OBJ) $(BONUS_OBJ)
	$(MAKE) $(NAME) SRC="$(SRC) $(SRC2)"

.PHONY: all clean fclean re bonus